spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 70
    metadata-map:
      zone: zone_A
  client:
    fetchRegistry: false #1
    eureka-server-connect-timeout-seconds: 60 #2
    eureka-service-url-poll-interval-seconds: 15 #3
    use-dns-for-fetching-service-urls: false #4
    prefer-same-zone-eureka: true #6
    healthcheck: #7
      enabled: true
    registerWithEureka: false
  server:
    renewal-percent-threshold: 0.85
    expected-client-Renewal-interval-seconds: 20